getyoti/yoti-dotnet-sdk

src/Yoti.Auth.Owin/YotiAuthenticationExtensions.cs
src/Yoti.Auth.Owin/YotiAuthenticationHandler.cs
src/Yoti.Auth.Owin/project.json
src/Yoti.Auth/YotiClientEngine.cs
src/Yoti.Auth/YotiUserProfile.cs
src/Yoti.Auth/project.json
test/Yoti.Auth.Tests/project.json

I created this pull request blindly to update the email and address fields. Not sure I can test this on a Mac.

Update Yoti fields

---

test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

Updated Microsoft.NET.Test.Sdk package so that the tests are also compatible with VS 2017

[SDK-72]: Updated Microsoft.NET.Test.Sdk package

---

src/Yoti.Auth/CryptoEngine.cs
src/Yoti.Auth/YotiClientEngine.cs

Cleaned up YotiClientEngine - moved relevant parts to CrypoEngine.cs, and broke up very lengthy method into a set of different methods.

[SDK-72]: Cleaned up YotiClientEngine

---

src/Example.sln
src/Example/Example.csproj
src/Example/packages.config
src/IdentityExample.sln
src/IdentityExample/IdentityExample.csproj
src/IdentityExample/packages.config
src/NuGet.Config
src/Yoti.Auth.Owin.nuspec
src/Yoti.Auth.nuspec
src/Yoti.Auth.sln

Since I added the projectUrl and iconUrl when I uploaded the package, I've added these to the .nuspec files, so that nothing else will need to be added for future publishes.

[SDK-91]: Added NuGet Package install configs, added fields to .nuspec files, updated example projects

---

src/Example/App_Start/BundleConfig.cs
src/Example/App_Start/FilterConfig.cs
src/Example/App_Start/RouteConfig.cs
src/Example/App_Start/Startup.Auth.cs
src/Example/App_Start/Startup.cs
src/Example/Controllers/AccountController.cs
src/Example/Controllers/HomeController.cs
src/Example/Data/ApplicationContext.cs
src/Example/Data/UserManager.cs
src/Example/Global.asax.cs
src/Example/Migrations/201609290943445_Initial.cs
src/Example/Migrations/Configuration.cs
src/Example/Models/User.cs
src/Example/Properties/AssemblyInfo.cs
src/IdentityExample/App_Start/BundleConfig.cs
src/IdentityExample/App_Start/FilterConfig.cs
src/IdentityExample/App_Start/IdentityConfig.cs
src/IdentityExample/App_Start/RouteConfig.cs
src/IdentityExample/App_Start/Startup.Auth.cs
src/IdentityExample/Controllers/AccountController.cs
src/IdentityExample/Controllers/HomeController.cs
src/IdentityExample/Controllers/ManageController.cs
src/IdentityExample/Global.asax.cs
src/IdentityExample/Migrations/201609291414520_InitialCreate.cs
src/IdentityExample/Migrations/Configuration.cs
src/IdentityExample/Models/AccountViewModels.cs
src/IdentityExample/Models/IdentityModels.cs
src/IdentityExample/Properties/AssemblyInfo.cs
src/IdentityExample/Startup.cs
src/IdentityExample/Web.config

[SDK-72]: Removed unnecessary references and updated IdentityExample to use config values

[SDK-72]: Removed unnecessary references and updated IdentityExample to use config values

---

README.md

Updated instructions in README after publishing the NuGet package to NuGet.org, as it no longer needs to be compiled.

[SDK-103]: Updated instructions in README 

---

src/Yoti.Auth/YotiClientEngine.cs

Added X-SDK and checked in the tests that this attribute is sent.

[SDK-112]: Added "X-SDK" identifier to headers sent in HTTP Request

---

src/Yoti.Auth/Conversion.cs
src/Yoti.Auth/HttpRequester.cs
src/Yoti.Auth/IHttpRequester.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/FakeHttpRequester.cs
test/Yoti.Auth.Tests/HttpRequester_Tests.cs
test/Yoti.Auth.Tests/YotiClientEngine_Tests.cs

Initial commit for signed requests. I think there is further opportunity for the extraction of functionality from YotIClientEngine, in a similar way to how Java is done, so that this class isn't doing so much, but thought I'd get some feedback on this part first. Tested with Example project and the standard GET request GetActivityDetails is working correctly

[SDK-246]: Signed requests

---

README.md
src/Yoti.Auth/Activity.cs
src/Yoti.Auth/Aml/AmlAddress.cs
src/Yoti.Auth/Aml/AmlException.cs
src/Yoti.Auth/Aml/AmlProfile.cs
src/Yoti.Auth/Aml/AmlResult.cs
src/Yoti.Auth/Aml/IAmlAddress.cs
src/Yoti.Auth/Aml/IAmlProfile.cs
src/Yoti.Auth/Aml/IAmlResult.cs
src/Yoti.Auth/Aml/RemoteAmlService.cs
src/Yoti.Auth/EndpointFactory.cs
src/Yoti.Auth/HttpRequester.cs
src/Yoti.Auth/Response.cs
src/Yoti.Auth/SignedMessageFactory.cs
src/Yoti.Auth/YotiClient.cs
src/Yoti.Auth/YotiClientEngine.cs
src/Yoti.Auth/YotiConstants.cs
test/Yoti.Auth.Tests/YotiClientEngine_Tests.cs
test/Yoti.Auth.Tests/YotiClient_Tests.cs

Did a bit of refactoring and tidying up as I went along.
Also changed the HTTP requests so all of the relevant information is propagated to the user.

[SDK-249]: AML Check

---

src/Example/Controllers/HomeController.cs
src/Example/Example.csproj
src/Example/Migrations/201710191343213_AddBase64Photo.cs
src/Example/Migrations/201802081633397_AddProfileAttributes.cs
src/Example/packages.config
src/Yoti.Auth.Owin/Provider/YotiAuthenticatedContext.cs
src/Yoti.Auth/Aml/IRemoteAmlService.cs
src/Yoti.Auth/Aml/RemoteAmlService.cs
src/Yoti.Auth/Yoti.Auth.csproj
src/Yoti.Auth/YotiClient.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/TestTools.cs
test/Yoti.Auth.Tests/YotiClientEngine_Tests.cs
test/Yoti.Auth.Tests/YotiClient_Tests.cs

- Added further tests
- Tidying up
- Bumped version
- Tested both AML & Profile retrieval functionality with new package
Will publish to NuGet once this PR is approved

[SDK-249]: Further AML Tests & Tidying up

---

src/Examples/45Example/45Example.csproj
src/Examples/45Example/Data/ApplicationContext.cs
src/Examples/CoreExample/.env.example
src/Examples/CoreExample/Controllers/AccountController.cs
src/Examples/CoreExample/Controllers/HomeController.cs
src/Examples/CoreExample/Views/Home/Index.cshtml
src/Yoti.Auth/Activity.cs
src/Yoti.Auth/ActivityDetail.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- Added ReceiptID to ActivityDetails
- Updated ActivityDetails items to be privately set
- Corrected package locations for 45Example project
- Changed CoreExample project to use inline QR code

[SDK-554] Adding ReceiptID to ActivityDetails

---

src/Yoti.Auth/Aml/IRemoteAmlService.cs
src/Yoti.Auth/Aml/RemoteAmlService.cs
src/Yoti.Auth/HeadersFactory.cs
src/Yoti.Auth/YotiClient.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/HeadersFactoryTests.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

SDK-623 Allow specification of HTTPClient

---

src/Examples/45Example/Controllers/HomeController.cs
src/Examples/CoreExample/Controllers/HomeController.cs
src/Yoti.Auth/ShareUrl/Policy/DynamicPolicy.cs
src/Yoti.Auth/ShareUrl/Policy/DynamicPolicyBuilder.cs
src/Yoti.Auth/ShareUrl/Policy/WantedAttribute.cs
src/Yoti.Auth/ShareUrl/Policy/WantedAttributeBuilder.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/DynamicPolicyBuilderTests.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/WantedAttributeBuilderTests.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/WantedAttributeMatcher.cs
test/Yoti.Auth.Tests/TestData/DynamicPolicy.json
test/Yoti.Auth.Tests/TestTools/ShareUrl.cs

Since it wasn't possible to make everything private which used the optional functionality, I've removed the optional parts for now. We can revert this change when optional attributes are enabled in the app.

SDK-980 Dynamic Scenarios - optional attributes

---

src/Yoti.Auth/Anchors/Anchor.cs
src/Yoti.Auth/Attribute/BaseAttribute.cs
test/Yoti.Auth.Tests/AnchorTests.cs

- Change Anchor value to be a single string
- Add to anchor test coverage

SDK-1025: Change Anchor Value

---

README.md
src/Examples/Aml/AmlExample/.env.example
src/Examples/Aml/AmlExample/AmlExample.csproj
src/Examples/Aml/AmlExample/Program.cs

- Choice of whether to use USA address is configured with an env variable

SDK-1046: Add USA example

---

src/Yoti.Auth/Profile/YotiProfile.cs

- I used an autoformatter for XML comments too, to ensure they don't go over a certain width.

SDK-992: Update attribute descriptions

---

README.md

- Update AgeVerification example, correct source retrieval var name. Will match dev docs too.

Update AgeVerification example, correct source retrieval var name

---

README.md

- Branching off **master**, as we are going to merge this in with the Dashboard -> Hub changes, before the v3.0.0 release.

SDK-1083: Update dev docs URL

---

src/Examples/Profile/45Example/45Example.csproj
src/Examples/Profile/45Example/Controllers/AccountController.cs
src/Examples/Profile/45Example/Models/DisplayAttribute.cs
src/Examples/Profile/45Example/Views/Account/Connect.cshtml
src/Examples/Profile/45Example/static/profile.css
src/Examples/Profile/CoreExample/Controllers/AccountController.cs
src/Examples/Profile/CoreExample/Models/DisplayAttribute.cs
src/Examples/Profile/CoreExample/Views/Account/Connect.cshtml
src/Examples/Profile/CoreExample/wwwroot/static/profile.css

- Will also add document_images once it's been added to the SDK
- I added a generic `GetValue` method which returns an object, in case we decide to do custom displays for other attributes

SDK-1058: Add Structured Postal Address to example project

---

src/Examples/Profile/45Example/Controllers/HomeController.cs
src/Examples/Profile/45Example/Views/Home/DynamicScenario.cshtml
src/Examples/Profile/45Example/Views/Home/Index.cshtml
src/Examples/Profile/45Example/secrets.config.example
src/Examples/Profile/45Example/static/index.css
src/Examples/Profile/CoreExample/.env.example
src/Examples/Profile/CoreExample/Controllers/AccountController.cs
src/Examples/Profile/CoreExample/Controllers/HomeController.cs
src/Examples/Profile/CoreExample/Views/Home/DynamicScenario.cshtml
src/Examples/Profile/CoreExample/Views/Home/Index.cshtml
src/Examples/Profile/CoreExample/wwwroot/static/index.css

- Removed APPLICATION_ID references also

SDK-1036: Add Modal to Example projects

---

src/Examples/Aml/AmlExample/.env.example
src/Examples/Profile/CoreExample/Dockerfile
src/Examples/Profile/CoreExample/docker-compose.override.yml
src/Examples/Profile/CoreExample/docker-compose.yml
src/Yoti.Auth/ShareUrl/DynamicScenarioBuilder.cs

- Update dockerfile after examples location change
- Also corrected Dynamic Scenario extension summary

Update dockerfile after examples location change

---

README.md

- See [README ](https://github.com/getyoti/yoti-dotnet-sdk/tree/SDK-976-AddSonarBadges) for badges

SDK-976: Add Sonar badges

---

README.md
src/Examples/Profile/47Example/47Example.csproj
src/Examples/Profile/47Example/Global.asax.cs
src/Examples/Profile/47Example/Web.config

- Cherry picked (see #148), applying to master
- Also cherry picked badges commit (see #140)

SDK-1381: Update packages location -> master

---

azure-pipelines.yml

- Update sonarcloud project name to match other SDKs
- Update version (3.3.0 currently released)

SDK-1389: Update sonarcloud 

---

azure-pipelines.yml
src/Yoti.Auth/Document/DocumentDetailsAttributeParser.cs
src/Yoti.Auth/Properties/Resources.Designer.cs
src/Yoti.Auth/Properties/Resources.resx
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests/DocumentDetailsAttributeParserTests.cs

- Allow any character in DocumentDetails value

SDK-1442: Update Document Details Parsing

---

test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

- It is installed in the Azure pipeline

Remove reportgenerator

---

.github/ISSUE_TEMPLATE/custom-template.md

Content at top of new issues: 
```
#
#
#
#
#
```

SDK-1480: Add custom issue template

---

src/Examples/Profile/CoreExample/CoreExample.csproj

Microsoft.CodeAnalysis packages needed to be updated in tandem, so doing them here rather than through dependabot

Update Microsoft.CodeAnalysis packages

---

azure-pipelines.yml
src/Yoti.Auth/Yoti.Auth.csproj

SDK-1298: Update version to 3.5.0

---

README.md

SDK-1421: Fix README link

---

azure-pipelines.yml
src/Examples/DocScan/DocScanExample/Controllers/HomeController.cs
src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml
src/Examples/Profile/47Example/47Example.csproj
src/Examples/Profile/47Example/Controllers/HomeController.cs
src/Examples/Profile/CoreExample/Controllers/HomeController.cs
src/Examples/Profile/CoreExample/CoreExample.csproj
src/Yoti.Auth/Constants/DocScanConstants.cs
src/Yoti.Auth/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilder.cs
src/Yoti.Auth/DocScan/Session/Create/Task/RequestedTextExtractionTaskConfig.cs
src/Yoti.Auth/DocScan/Session/Retrieve/DocumentIdPhotoResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Resource/IdDocumentResourceResponse.cs
src/Yoti.Auth/Yoti.Auth.csproj
test.sh
test/Yoti.Auth.Tests/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilderTests.cs
test/Yoti.Auth.Tests/Share/ExtraDataConverterTests.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- Add chipdata, DocumentIdPhoto
- Update extra data tests to use same format as other Expiry Dates
- Remove location constraint from Dynamic Scenario Example
- Don't run Code Analysis on build for 4.7 Example project (MS guidelines, matches other projects)
- Update packages and target framework of CoreExample project
- Remove Sandbox tests from pre-commit hook after moving to own repo

SDK-1636: Chip Data

---

src/Examples/DocScan/DocScanExample/Views/Home/Index.cshtml

See SDK-1678
If this all looks ok, will replicate to other SDK's demo projects.
Going into master as we want to get this out now, and it doesn't need to be in a release, will merge into development after

SDK-1679: Update iframe html to allow full screen

---

src/Examples/DocScan/DocScanExample/Controllers/HomeController.cs
src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml

- Committed last week, forgot to create a PR

SDK-1748: Remove FaceMap from demo

---

src/Examples/Profile/47Example/47Example.csproj
src/Examples/Profile/47Example/packages.config
src/Examples/Profile/CoreExample/CoreExample.csproj
src/Yoti.Auth/ShareUrl/Policy/SourceConstraintBuilder.cs
src/Yoti.Auth/Web/RequestBuilder.cs
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

For CA fixes, I was thinking that:
```cs
private bool _softPreference = false;	
```
is more explicit than:
```cs
private bool _softPreference;	
```
But I don't think I feel strongly about this enough to create an exception!

NA: Update packages

---

src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml
src/Yoti.Auth/DocScan/Session/Create/SessionSpecification.cs
src/Yoti.Auth/DocScan/Session/Create/SessionSpecificationBuilder.cs
src/Yoti.Auth/DocScan/Session/Retrieve/GetSessionResult.cs
test/Yoti.Auth.Tests/DocScan/DocScanClientTests.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/SessionSpecificationBuilderTests.cs

- Ability to block biometric consent
- `SessionSpecificationBuilder.WithBlockBiometricConsent`
- `GetSessionResult.BiometricConsentTimestamp`

SDk-1738: Add ability to block biometric consent

---

src/Examples/Profile/47Example/Controllers/HomeController.cs
src/Yoti.Auth/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckBuilder.cs
src/Yoti.Auth/DocScan/Session/Create/Check/RequestedDocumentAuthenticityConfig.cs
src/Yoti.Auth/DocScan/Session/Create/Check/RequestedFaceMatchCheckBuilder.cs
src/Yoti.Auth/DocScan/Session/Create/Task/RequestedTextExtractionTaskBuilder.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/Check/RequestedDocumentAuthenticityCheckBuilderTests.cs
test/Yoti.Auth.Tests/ShareUrl/Extensions/ThirdPartyAttributeExtensionBuilderTests.cs
test/Yoti.Auth.Tests/ValidationTests.cs

- RequestedDocumentAuthenticityCheckBuilder.
- WithManualCheckAlways()
- WithManualCheckFallback()
- WithManualCheckNever()

SDK-1731: Doc Auth: manual fallback

---

src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml
src/Yoti.Auth/DocScan/Session/Retrieve/PageResponse.cs

- accessor for `Frames` in `PageResponse` (`Yoti.Auth.DocScan.Session.Retrieve.PageResponse.Frames`)

SDK-1771: Add document page response frames

---

src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml
src/Yoti.Auth/DocScan/Session/Retrieve/Resource/ResourceContainer.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Resource/SupplementaryDocResourceResponse.cs

- Default supp. doc. lists to be an empty list
- Update demo to check for null lists

SDK-1705: Default supp doc Lists to empty list, update demo

---

azure-pipelines.yml
src/Yoti.Auth/Yoti.Auth.csproj

Minor version bumped to `3.9.0`

NA: Bump minor version to 3.9.0

---

src/Examples/Profile/47Example/47Example.csproj
src/Examples/Profile/47Example/Web.config
src/Examples/Profile/CoreExample/Dockerfile
src/Yoti.Auth/Yoti.Auth.csproj

- Reformatted .csproj files, please use the "ignore whitespace" option when reviewing:
- Update .NET Core Example to use .NET Core 3.1

NA: Use .NET Core 3.1 for example

---

src/Yoti.Auth/Constants/DocScanConstants.cs
src/Yoti.Auth/DocScan/DocScanClient.cs
src/Yoti.Auth/DocScan/DocScanService.cs
src/Yoti.Auth/DocScan/Session/Create/FaceCapture/CreateFaceCaptureResourcePayload.cs
src/Yoti.Auth/DocScan/Session/Create/FaceCapture/CreateFaceCaptureResourcePayloadBuilder.cs
src/Yoti.Auth/DocScan/Session/Create/FaceCapture/UploadFaceCaptureImagePayload.cs
src/Yoti.Auth/DocScan/Session/Create/FaceCapture/UploadFaceCaptureImagePayloadBuilder.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Check/GeneratedProfileResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/CreateFaceCaptureResourceResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/FaceCaptureImageResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/FaceCaptureResourceResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Resource/AllowedSourceResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Resource/ResourceContainer.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Resource/ResourceResponse.cs
src/Yoti.Auth/Validation.cs
src/Yoti.Auth/Web/RequestBuilder.cs
test/Yoti.Auth.Tests/DocScan/DocScanClientTests.cs
test/Yoti.Auth.Tests/DocScan/DocScanServiceTests.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/FaceCapture/CreateFaceCaptureResourcePayloadBuilderTests.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/FaceCapture/UploadFaceCaptureImagePayloadBuilderTests.cs
test/Yoti.Auth.Tests/DocScan/Session/Retrieve/Check/CheckResponseTests.cs
test/Yoti.Auth.Tests/TestTools/AssertExtensions.cs
test/Yoti.Auth.Tests/Web/RequestBuilderTests.cs

Add Face Capture Resource to IDV with relevant tests
Add test for GeneratedProfileResponse

SDK-1971 Add Face Capture Resource To IDV

---

src/Yoti.Auth/DocScan/Session/Create/Check/RequestedWatchlistAdvancedCaConfig.cs

IDV remove reported code smell

---

src/Yoti.Auth/ProtoBuf/Attribute/Attribute.cs
src/Yoti.Auth/ProtoBuf/Attribute/ContentType.cs
src/Yoti.Auth/ProtoBuf/Attribute/List.cs
src/Yoti.Auth/ProtoBuf/Attribute/Signing.cs
src/Yoti.Auth/ProtoBuf/Share/DataEntry.cs
src/Yoti.Auth/ProtoBuf/Share/ExtraData.cs
src/Yoti.Auth/ProtoBuf/Share/IssuingAttributes.cs
src/Yoti.Auth/ProtoBuf/Share/ThirdPartyAttribute.cs
src/Yoti.Auth/Protobuf/Common/EncryptedData.cs
src/Yoti.Auth/Protobuf/Common/SignedTimestamp.cs

- generated protobuf files after .proto updates

SDK-2073: Update generated protobuf files

---

src/Yoti.Auth/DocScan/Session/Create/SessionSpecification.cs
src/Yoti.Auth/DocScan/Session/Create/SessionSpecificationBuilder.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/SessionSpecificationBuilderTests.cs
test/Yoti.Auth.Tests/ShareUrl/DynamicScenarioBuilderTests.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/DynamicPolicyBuilderTests.cs
test/Yoti.Auth.Tests/TestData/IdentityProfiles.cs
test/Yoti.Auth.Tests/TestTools/ShareUrl.cs

SDK-2095 Add Identity Profile Requirements to Request IDV

---

src/Yoti.Auth/Attribute/AttributeConverter.cs
src/Yoti.Auth/Attribute/BaseAttribute.cs
src/Yoti.Auth/Attribute/YotiAttribute.cs
src/Yoti.Auth/Profile/BaseProfile.cs
test/Yoti.Auth.Tests/AttributeConverterTests.cs
test/Yoti.Auth.Tests/TestTools/Profile.cs
test/Yoti.Auth.Tests/YotiProfileTests.cs

- `GetId()` to Yoti attribute:
```csharp
attribute.GetId();
```
- `GetAttributeById()` to Yoti profile:
```csharp
var selfie = profile.GetAttributeById<Yoti.Auth.Images.Image>("attribute_id");
var documentImages = profile.GetAttributeById<List<Yoti.Auth.Images.Image>>("attribute_id_2");
```

SDK-2089: Add GetAttributeById

---

src/Examples/Profile/CoreExample/Controllers/AccountController.cs
src/Examples/Profile/CoreExample/Views/Account/Connect.cshtml

- Identity Profile Report attribute to example project

SDK-2056: Add Identity Profile Report attribute to example project

---

src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml
src/Yoti.Auth/Constants/DocScanConstants.cs
src/Yoti.Auth/DocScan/Session/Create/Check/Advanced/RequestedTypeListSources.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Check/CheckResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Check/ThirdPartyIdentityFraudOneCheckResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/GetSessionResult.cs
test/Yoti.Auth.Tests/DocScan/Session/Retrieve/Check/CheckResponseTests.cs
test/Yoti.Auth.Tests/DocScan/Session/Retrieve/GetSessionResultTests.cs

Mod whitespace to neaten in RequestedTypeListSources also

SDK-2114: Add Third Party Identity Fraud Check Result To IDV

---

src/Examples/Profile/CoreExample/Controllers/HomeController.cs
src/Examples/Profile/CoreExample/Views/Account/Connect.cshtml
src/Examples/Profile/CoreExample/Views/Home/DBSCheck.cshtml
src/Examples/Profile/CoreExample/Views/Home/DBSStandard.cshtml

- Demo page (at <https://localhost:44344/dbs-check>), which uses the dynamic scenario builder to request a DBS Check (Standard) with the following payload:
```json
{
"scheme": {
"objective": "STANDARD",
"type": "DBS"
},
"trust_framework": "UK_TFIDA"
}
```

SDK-2135: Add DBS Check page

---

src/Yoti.Auth/ActivityDetailsParser.cs
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

YotiProfileException Message no longer breaks onto two lines
Mods to fix minor code smells from previous [PR](https://github.com/getyoti/yoti-dotnet-sdk/pull/380)

SDK-2140: Minor Fixes to Error Code Surfacing

---

src/Yoti.Auth/Constants/DocScanConstants.cs
src/Yoti.Auth/DocScan/Session/Create/NotificationConfigBuilder.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/NotificationConfigBuilderTests.cs

**Added**
- Add support for requesting the profile preview
**Requested With**
```csharp
NotificationConfig notificationConfig =
new NotificationConfigBuilder()
.ForClientSessionCompletion()
.Build();
```

SDK-2209 added session completed notification and tests

---

src/Examples/Aml/AmlExample/AmlExample.csproj
src/Examples/DocScan/DocScanExample/Controllers/DbsController.cs
src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml
src/Yoti.Auth/DocScan/DocScanService.cs
src/Yoti.Auth/DocScan/Session/Create/SessionSpecification.cs
src/Yoti.Auth/DocScan/Session/Create/SessionSpecificationBuilder.cs
src/Yoti.Auth/DocScan/Session/Retrieve/AdvancedIdentityProfile/AdvancedIdentityProfilePreviewResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/AdvancedIdentityProfile/AdvancedIdentityProfileResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/AdvancedIdentityProfile/FailureReasonResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/GetSessionResult.cs
src/Yoti.Auth/ShareUrl/Policy/DynamicPolicy.cs
src/Yoti.Auth/ShareUrl/Policy/DynamicPolicyBuilder.cs
test/Yoti.Auth.Tests.Common/Yoti.Auth.Tests.Common.csproj
test/Yoti.Auth.Tests/DocScan/DocScanClientTests.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/SessionSpecificationBuilderTests.cs
test/Yoti.Auth.Tests/DocScan/Session/Retrieve/GetSessionResultTests.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/DynamicPolicyBuilderTests.cs
test/Yoti.Auth.Tests/TestData/GetSessionResultWithAdvancedIdentityProfile.json
test/Yoti.Auth.Tests/TestData/IdentityProfiles.cs
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

- Added advanced Identity Profile for Share and Idv

Sdk 2368 net add support for advanced identity profiles to share v 1 v 2 and examples

---

src/Examples/DocScan/DocScanExample/Views/IdVerify/Success.cshtml
src/Yoti.Auth/DocScan/Session/Retrieve/ExpandedDocumentFieldResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/Resource/IdDocumentResourceResponse.cs

SDK-2341: added support to retrieve expanded doc fields and media, added success page example

SDK-2341: added support to retrieve expanded doc fields and media

---

src/Yoti.Auth/ShareUrl/Policy/DynamicPolicyBuilder.cs
src/Yoti.Auth/ShareUrl/Policy/WantedAttribute.cs
src/Yoti.Auth/ShareUrl/Policy/WantedAttributeBuilder.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/WantedAttributeBuilderTests.cs
test/Yoti.Auth.Tests/TestData/DynamicPolicy.json

Added / changed structure of wanted attribute and made optional as parameter

Sdk 2363 net check for and add optional attribute configuration to sdk

---

src/Examples/DocScan/DocScanExample/Controllers/DbsController.cs
src/Examples/DocScan/DocScanExample/Controllers/HomeController.cs
src/Yoti.Auth/DocScan/DocScanService.cs

* update example session configurations
* IN5631 Updated to remove unsupported dotnet versions
* IN5631 Updated tests for dotnet version support

SDK-2382: Update IDV example project defaults (#440)
