test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

Included .pem files in build output, as this was behaviour was lost during the migration to VS2017

[SDK:72]: Included .pem files in build output

---

src/Yoti.Auth.sln

Removed global.json file, which is no longer required in VS2017 (this information is captured in the new .csproj file). This seems to have been missed out of the migration, but it should have been removed - see https://github.com/dotnet/project-system/issues/1184

[SDK-72]: Removed global.json file

---

src/Yoti.Auth.Owin/Yoti.Auth.Owin.csproj
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests/RunOpenCover.bat
test/Yoti.Auth.Tests/RunReportGenerator.bat
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

Set up project to work with OpenCover & ReportGenerator, so that we can generate code coverage reports

[SDK-72]: Set up project to work with OpenCover & ReportGenerator

---

test/Yoti.Auth.Tests/RunOpenCover.bat

Excluded assemblies produced by the Google.Protobuf NuGet package. These are auto-generated, and contain code which we aren't utlising in this project. It doesn't make sense to write code to test the parts which we're not using. For the next check-in I'll look at testing every part of this ProtoBuf package that we integrate with.

[SDK-72]: Excluded Google.Protobuf assemblies from Code Coverage

---

src/Yoti.Auth/HttpRequester.cs
src/Yoti.Auth/IHttpRequester.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/FakeHttpRequester.cs
test/Yoti.Auth.Tests/FakeHttpResponseHandler.cs
test/Yoti.Auth.Tests/HttpRequester_Tests.cs
test/Yoti.Auth.Tests/YotiClientEngine_Tests.cs

This Required a small amount of restructuring to allow the FakeHttpResponseHandler to be incorporated

[SDK-72]: Added Tests for HttpRequester class

---

src/Yoti.Auth.Owin.nuspec
src/Yoti.Auth.Owin/Properties/AssemblyInfo.cs
src/Yoti.Auth.Owin/Yoti.Auth.Owin.csproj
src/Yoti.Auth.nuspec
src/Yoti.Auth/Properties/AssemblyInfo.cs
src/Yoti.Auth/Yoti.Auth.csproj

After renaming the solution and project names, it didn't seem right to have both being called Yoti. After researching traditional naming structures, it seemed that Company.ProductName.Project is the best way to go, so I have kept the Project as Yoti.Auth. However, I have changed the PackageId to be Yoti, so that we can reserve this on NuGet, and the user types 
`Install-Package Yoti` to install.
I have changed the version to be 2.0.0. Technically, it could have been 1.0.0, as it's a different package name, but I thought this might be confusing, given the choice between Yoti.Auth 1.1.0, and Yoti 1.0.0.
I removed some of the references in Yoti.Auth.Owin.nuspec, as these are not required. 
I have tested these changes with a local NuGet package repository with the Example and IdentityExample …

[SDK-91]: Modified assemblies for new NuGet package

---

src/Yoti.Auth.Owin.nuspec
src/Yoti.Auth.nuspec

Slight change from spec in changing " .net SDK for Yoti API support for Login" to ".NET SDK, providing Yoti API support for Login" (so we're not using 'for' twice)

[SDK-91]: Updated description and tags of NuGet package specification

---

RunOpenCover.bat
RunReportGenerator.bat

Due to different NuGet configurations putting the \packages folder in different places, I've moved the .bat files which handle the respective OpenCover and ReportGenerator operations to the root of the repo. This will mean it will find other configurations of where the \packages folder might reside. Updated the content of the .bat files themselves to reflect this, and did a small amount of tidying up.

[SDK-93]: Made batch files more user-friendly

---

src/Example/Controllers/HomeController.cs
src/Example/Data/UserManager.cs
src/Example/Views/Home/Index.cshtml

Example project was crashing when photo was not requested (and consequently supplied) by the application. Also found other bug in the process - if the application changes the details requested of the user, this new information is never added to the user profile.

[SDK-95]: Fixed bug where Example project was crashing when no photo requested

---

NuGet.Config
src/Example/Example.csproj
src/Example/Web.config
src/Example/packages.config
src/Yoti.Auth.nuspec
src/Yoti.Auth/YotiClientEngine.cs

1. Changed header to X-Yoti-SDK
2. Published new NuGet package
3. Updated example project to use this new package
4. Fixed error with Package Manager Console inside the example project ([SO1](https://stackoverflow.com/questions/41901031/error-packagemanager-console), [SO2](https://stackoverflow.com/questions/31770339/nuget-package-manager-update-3-1-1-0-broken/32402220#32402220))
5. Minor change to casing of NuGet package folder, as this is the casing that is currently set in the example projects

[SDK-128]: Updated HTTP header to X-Yoti-SDK

---

README.md

Fixed Documentation Link
External links needs to be prefixed with `https://` otherwise Github will prefix it with 
`https://github.com/getyoti/yoti-dotnet-sdk/blob/master/` as it thinks it is an internal link.
README.md

Fixed Documentation Link in README.md

---

.travis.yml
README.md
src/Examples/45Example/45Example.csproj
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

- Since the SDK builds against multiple frameworks, some of which are only available on Windows, we need to have Windows as the OS.
- Modification to the .csproj file is removing a property that VS 2012 added, which isn't needed (and was causing the build to fail on Travis) ([SO answer here](https://stackoverflow.com/questions/19718281/external-vs2013-build-error-error-msb4019-the-imported-project-path-was-not))
- `<IsTestProject>` is required to tell the dotnet compiler that tests should be run for that project. I'm following the issue which will allow us to suppress the output which produces: `Skipping running test for project C:\Users\travis\build\getyoti\yoti-dotnet-sdk\src\Yoti.Auth\Yoti.Auth.csproj. To run tests with dotnet test add "<IsTestProject>true<IsTestProject>" property to …

SDK-881: Travis

---

src/Yoti.Auth/AttributeConverter.cs
src/Yoti.Auth/ProfileParser.cs
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests/ActivityTests.cs
test/Yoti.Auth.Tests/AttributeConverterTests.cs
test/Yoti.Auth.Tests/ProfileParserTests.cs

- Testing that the remaining attributes continue to be parsed required a small amount of reorganising.
- I also noticed there was no test coverage for the exceptions in ProfileParser, so I added those. 
- Using [NLog](https://nlog-project.org/) in favour of other logging tools as it is open-source, seems to be the de facto standard, and is actively maintained. It also seems to be the [most efficient](https://www.loggly.com/blog/benchmarking-5-popular-net-logging-libraries/). We are using the MS logging in the example projects, so I will look at swapping that out in future.

SDK-893: Update UNDEFINED Content type handling

---

src/Yoti.Auth/Document/DocumentDetails.cs
src/Yoti.Auth/YotiProfile.cs

- See ticket SDK-694 for more info - have opted to not make any other changes as part of that ticket
- Added to descriptions of DateTime objects to explain the times will default to 00:00:00
- Added remaining DocumentDetails descriptions - please review

SDK-694: DateTimes & Descriptions

---

.gitignore
README.md
src/Yoti.Auth/Constants/ApplicationProfile.cs
src/Yoti.Auth/Web/HttpRequester.cs
src/Yoti.Auth/YotiClient.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/TestData/TestAnchors.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- Add DocumentDetails to README
- Make Yoti API configurable, for use with the wrapper application
- Creating URIs seem to sometimes result in a trailing slash, which caused a double slash when combined with the endpoint. I created `CreateRequestUri` to remove this trailing slash if it's present
- Made ApplicationProfile consts public (like UserProfile), so we can reference them externally

SDK-468: Wrapper App changes

---

src/Yoti.Auth/ShareUrl/Policy/DynamicPolicy.cs
src/Yoti.Auth/ShareUrl/Policy/DynamicPolicyBuilder.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/DynamicPolicyBuilderTests.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- WithPinAuthentication(enabled:false) / WithSelfieAuthentication(enabled:false) now removes that AuthType from the Policy, and WithAuthType now has `enabled` field, allowing other auth types to be removed too
- Ensuring uniqueness for AuthTypes by using HashSet instead of a List

SDK-1094: Allow removal of authType, ensure uniqueness

---

src/Yoti.Auth/Web/HeadersFactory.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/GlobalSuppressions.cs
test/Yoti.Auth.Tests/Web/HeadersFactoryTests.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- Update Request Builder to not include Auth Key Header by default
- `.Callback` stores the parameters which the mockMessageHandler was called with, which we then inspect to check the header is present

SDK-1205: Update Request Builder 

---

src/Examples/Aml/AmlExample/AmlExample.csproj
src/Examples/Profile/45Example/45Example.csproj
src/Examples/Profile/45Example/GlobalSuppressions.cs
src/Examples/Profile/45Example/packages.config
src/Examples/Profile/CoreExample/CoreExample.csproj
src/Examples/Profile/CoreExample/GlobalSuppressions.cs
src/Yoti.Auth.Sandbox/Yoti.Auth.Sandbox.csproj
src/Yoti.Auth.Sandbox/YotiSandboxClient.cs
src/Yoti.Auth/Anchors/AnchorCertificateParser.cs
src/Yoti.Auth/Constants/Web.cs
src/Yoti.Auth/Web/HeadersFactory.cs
src/Yoti.Auth/Yoti.Auth.csproj
src/Yoti.Auth/YotiClient.cs
src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Sandbox.Tests/Yoti.Auth.Sandbox.Tests.csproj
test/Yoti.Auth.Tests.Common/Yoti.Auth.Tests.Common.csproj
test/Yoti.Auth.Tests/Web/HeadersFactoryTests.cs
test/Yoti.Auth.Tests/Web/RequestBuilderTests.cs
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- Have reverted to specifying a version in Yoti.Auth.Tests for Microsoft.AspNetCore.All after MS changed their advice - https://github.com/aspnet/AspNetCore.Docs/issues/6430#issuecomment-403296211
- Add "Treat Warnings As Errors"
- Rename (Constants.)"Web" to "Api" to avoid namespace conflict

SDK-914: FXCop Fixes, package updates

---

README.md
src/Yoti.Auth/Anchors/AnchorCertificateParser.cs
src/Yoti.Auth/Conversion.cs
src/Yoti.Auth/Yoti.Auth.csproj
src/Yoti.Auth/YotiClientEngine.cs

- Will wait for SDK v3.0.0 release before merging
- .NET Core 3.0 requires MS Build Tools 16 to compile, which is only included in Visual Studio 2019. I've chosen to not include this for now, as it will restrict who can compile the SDK (both internally and externally)
- Additionally Travis doesn't support .NET Core App 2.2 yet unfortunately, so I've only added 2.1

SDK-1225: Target frameworks

---

azure-pipelines.yml

- View last run in GitHub - https://github.com/getyoti/yoti-dotnet-sdk/runs/371051368
- Azure
- Tests - https://dev.azure.com/yoti/Dotnet%20SDK/_build/results?buildId=198&view=ms.vss-test-web.build-test-results-tab
- Code Coverage - https://dev.azure.com/yoti/Dotnet%20SDK/_build/results?buildId=198&view=codecoverage-tab
- SonarCloud for this branch - https://sonarcloud.io/dashboard?id=getyoti_yoti-dotnet-sdk&branch=SDK-1242-Coverage&resolved=false

SDK-1242: Add Coverage reporting

---

src/Yoti.Auth/Constants/Format.cs
src/Yoti.Auth/Share/ThirdParty/ThirdPartyAttributeConverter.cs
test/Yoti.Auth.Tests/Anchors/AnchorTests.cs
test/Yoti.Auth.Tests/Anchors/SignedTimestampTests.cs
test/Yoti.Auth.Tests/Share/ExtraDataConverterTests.cs
test/Yoti.Auth.Tests/Share/ThirdParty/ThirdPartyAttributeConverterTests.cs
test/Yoti.Auth.Tests/ShareUrl/Extensions/ThirdPartyAttributeExtensionBuilderTests.cs

See [DateTime.ToString() - Custom date and time format strings](https://docs.microsoft.com/en-us/dotnet/standard/base-types/custom-date-and-time-format-strings):
- `fff`: The milliseconds in a date and time value.
- `zzz`: Hours and minutes offset from UTC.
- `ffffff`: The millionths of a second in a date and time value.
- `Z`; Hours offset from UTC, with no leading zeros.
So switching from `fffzzz` to `ffffffZ` produces `2006-01-02T22:04:05.000Z` instead of `2006-01-02T22:04:05.000+00:00`, which are both acceptable RFC3339 formats.
I've updated all the DateTime.ToString() to use this format, to avoid duplication.

SDK-1364: Allow all RFC3339 dates for Expiry Date

---

test/Yoti.Auth.Sandbox.Tests/Profile/Request/Attribute/SandboxAnchorTests.cs
test/Yoti.Auth.Sandbox.Tests/YotiSandboxClientTests.cs
test/Yoti.Auth.Tests/ActivityDetailsParserTests.cs
test/Yoti.Auth.Tests/ActivityTests.cs
test/Yoti.Auth.Tests/AmlProfileTests.cs
test/Yoti.Auth.Tests/Anchors/AnchorTests.cs
test/Yoti.Auth.Tests/ApplicationProfileTests.cs
test/Yoti.Auth.Tests/AttributeConverterTests.cs
test/Yoti.Auth.Tests/ShareUrl/Policy/DynamicPolicyBuilderTests.cs
test/Yoti.Auth.Tests/UserProfileTests.cs
test/Yoti.Auth.Tests/Verifications/AgeVerificationTests.cs
test/Yoti.Auth.Tests/Web/RequestBuilderTests.cs
test/Yoti.Auth.Tests/YotiAttributeTests.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs
test/Yoti.Auth.Tests/YotiClientTests.cs

- This was based on the idea that tests should always describe what they are doing, so it shouldn't be necessary to additionally read through the steps to work out what it is testing. This was the case in most of the tests, but this changeset is ensuring the tests are named consistently throughout.
- I don't think _all_ of the changes were entirely necessary (e.g. just adding "should), but I just thought that whilst I was renaming the tests I might as well make them all consistent.

SDK-682: Rename tests

---

src/Yoti.Auth/CryptoEngine.cs
test/Yoti.Auth.Tests/CryptoEngineTests.cs

- Added empty string validation when attempting to decrypt a token

SDK-1386: Add validation and tests for one time use token varations

---

src/Examples/Profile/47Example/47Example.csproj
src/Examples/Profile/47Example/Global.asax.cs
src/Examples/Profile/47Example/Web.config

This seems to be a problem in that the "packages" folder is created differently on the Azure environment than on other machines. I think it might be a problem when using Visual Studio 2019, but I'm not sure of the root cause, it could be NuGet too. 
This change tries to import the package from both of the locations it could be present at, and I'm hoping this will be addressed and fixed so we can have consistent build environments both on Azure and elsewhere.
I reverted adding the static modifier, as this was causing a 403 error, I presume because it required to be non-static in order to be picked up.

SDK-1381: Packages location

---

azure-pipelines.yml
src/Yoti.Auth/Yoti.Auth.csproj
src/Yoti.Auth/YotiClient.cs
test/Yoti.Auth.Tests/Verifications/AgeVerificationTests.cs
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj
test/Yoti.Auth.Tests/YotiClientTests.cs

- Use .env variable for `YOTI_API_URL` if present,
- __except__ when overridden with `YotiClient.OverrideApiUri`
- Also updated target framework of tests

SDK-1505: Use .env variable for YOTI_API_URL

---

src/Examples/Profile/47Example/Web.config
src/Examples/Profile/47Example/packages.config
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

- Update packages, add explicit NetStandard reference
- Netstandard is needed for some references in the `Connect.cshtml` razor view

Update packages, add explicit NetStandard reference

---

src/Yoti.Auth/Constants/Format.cs
test/Yoti.Auth.Tests/Anchors/SignedTimestampTests.cs
test/Yoti.Auth.Tests/Share/ThirdParty/ThirdPartyAttributeConverterTests.cs
test/Yoti.Auth.Tests/ShareUrl/Extensions/ThirdPartyAttributeExtensionBuilderTests.cs

- The constant used was incorrectly called "RFC3339PatternMilli", when it was actually microseconds.
- Have kept the test "ShouldParseAllValidRFC3339Dates" in ThirdPartyAttributeConverterTests, even though we should only expecte Millisecond timestamps, as didn't see the harm in allowing more.

SDK-1587: Format ExpiryDate of ThirdPartyAttributeExtension w/ ms

---

src/Yoti.Auth/YotiClientEngine.cs
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- If the token is an empty string, an unhelpful error is thrown about block size, so this is to add validation before that point

SDK-1386: Throw exception for null or empty token

---

src/Yoti.Auth/YotiClient.cs
test/Yoti.Auth.Tests/YotiClientTests.cs

- The API URL setting method was not called for `YotiClient(HttpClient httpClient, string sdkId, AsymmetricCipherKeyPair keyPair)`
- Refactor client initialisation so that entrypoints go through the same path
I attempted to add "YotiClient(string sdkId, AsymmetricCipherKeyPair keyPair)" as an initialiser option.
This strangely causes a problem when building the .NET 4.7 Example project. When initialising the YotiClient with a **DIFFERENT** initialiser, the codepath does not go through this new method, but the compiler seems to get confused, and think that a reference is required to BouncyCastle/Portable.BouncyCastle.
I think this is a bug with .NET. Using named parameters from integrator's code gets round this, but I think having clients specify `new HttpClient()` when calling with …

SDK-1595: Refactor client initialisation

---

src/Yoti.Auth/DocScan/DocScanService.cs
test/Yoti.Auth.Tests/DocScan/DocScanClientTests.cs

-  Don't assume response always has content
- for 204 (No content), return null instead (currently throws exception)

SDK-1811: Don't assume response always has content

---

src/Examples/DocScan/DocScanExample/DocScanExample.csproj
src/Examples/Profile/47Example/47Example.csproj
src/Examples/Profile/CoreExample/CoreExample.csproj
src/Examples/Profile/CoreExample/Startup.cs
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

- Package updates before working on 3rd Party Identity Checks
- Got a warning that .NET Core app 2.2 is deprecated, so upgraded to 3.1. This required some small changes, see https://docs.microsoft.com/en-us/aspnet/core/migration/22-to-30?view=aspnetcore-3.0&tabs=visual-studio#migrate-startupconfigure (also required removing the `<PackageReference Include="Microsoft.AspNetCore.App"` reference

NA: Package updates

---

src/Yoti.Auth/DocScan/Session/Create/SessionSpecification.cs
src/Yoti.Auth/DocScan/Session/Create/SessionSpecificationBuilder.cs
test/Yoti.Auth.Tests/DocScan/Session/Create/SessionSpecificationBuilderTests.cs

Add Session Deadline To IDV
Modify ClientSessionTokenTtl to make it nullable and so omitted when Relying Business has not set

SDK-1979:Add Session Deadline To IDV

---

src/Yoti.Auth/DocScan/Session/Create/SessionSpecification.cs
src/Yoti.Auth/DocScan/Session/Create/SessionSpecificationBuilder.cs

As previously suggested by @echarrod the resources_ttl now needs to be omitted when not set.

IDV Fix Resources TTL

---

src/Yoti.Auth/Constants/UserProfile.cs
src/Yoti.Auth/Profile/YotiProfile.cs
test/Yoti.Auth.Tests/ActivityTests.cs
test/Yoti.Auth.Tests/TestData/RTWIdentityProfileReport.json
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

- Identity Profile Report attribute (type JSON)
- See [RTWIdentityProfileReport.json](https://github.com/getyoti/yoti-dotnet-sdk/blob/776f4e852cb3ab50fa1251952940b039686fcdd0/test/Yoti.Auth.Tests/TestData/RTWIdentityProfileReport.json) for an example of the JSON value

SDK-2056: Add Identity Profile Report attribute

---

src/Yoti.Auth/Profile/BaseProfile.cs

- Update FindAttributesStartingWith to loop through each attribute with the same name, after AttributeCollection was added in https://github.com/getyoti/yoti-dotnet-sdk/pull/122
We can't unit test this for this specific scenario as the logic is from the Age Over/Under attribute being derived before the attribute list is shared. This is covered in integration tests though

SDK-1150: Fix FindAttributesStartingWith for Derived Attributes 

---

src/Yoti.Auth/DocScan/Session/Retrieve/GetSessionResult.cs
src/Yoti.Auth/DocScan/Session/Retrieve/IdentityProfile/FailureReasonResponse.cs
src/Yoti.Auth/DocScan/Session/Retrieve/IdentityProfile/IdentityProfileResponse.cs
test/Yoti.Auth.Tests/DocScan/DocScanClientTests.cs
test/Yoti.Auth.Tests/TestData/GetSessionResultWithIdentityProfile.json
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj

- IdentityProfile to IDV GetSessionResult:
```csharp
IdentityProfileResponse identityProfile = getSessionResult.IdentityProfile;
string subjectId = identityProfile.SubjectId;
string result = identityProfile.Result;
string failureReasonCode = identityProfile.FailureReason.ReasonCode;
```
example IdentityProfile.Report value:
```json
"trust_framework": "UK_TFIDA",
"schemes_compliance": [{
"scheme": {
"type": "DBS",
"objective": "STANDARD"
},
"requirements_met": true,
"requirements_not_met_info": "info here"
}
],
"media": {
"id": "c69ff2db-6caf-4e74-8386-037711bbc8d7",
"type": "IMAGE",
"created": "2022-03-29T11:39:24Z",
"last_updated": "2022-03-29T11:39:24Z"
}
```
MediaID can be retrieved with:
```csharp
string mediaId = getSessionResult.IdentityProfile.Report["media"]["id"]
```
and used to …

SDK-2096: Add IDV Identity Profile

---

src/Yoti.Auth/Profile/BaseProfile.cs

- Missed a code smell in https://github.com/getyoti/yoti-dotnet-sdk/pull/362
"SonarQube: Loops should be simplified with "LINQ" expressions"
> When a loop is filtering, selecting or aggregating, those functions can be handled with a clearer, more concise LINQ expression instead.
I've run the integration tests against this branch to check it doesn't modify behaviour

NA: Fix Sonar code smell

---

src/Yoti.Auth/ActivityDetailsParser.cs
src/Yoti.Auth/Exceptions/YotiProfileException.cs
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests/TestData/ShareFailure.json
test/Yoti.Auth.Tests/TestData/ShareFailureMinimal.json
test/Yoti.Auth.Tests/TestData/ShareFailureMissingErrorCode.json
test/Yoti.Auth.Tests/TestData/ShareFailureMissingErrorDetails.json
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

to surface error details for failure receipts for Digital ID App Shares

SDK-2140: Add ErrorCode and ResponseContent to YotiProfileException

---

src/Examples/Profile/CoreExample/CoreExample.csproj
src/Yoti.Auth/ActivityDetailsParser.cs
src/Yoti.Auth/Exceptions/YotiProfileException.cs
src/Yoti.Auth/Yoti.Auth.csproj
test/Yoti.Auth.Tests.Common/Yoti.Auth.Tests.Common.csproj
test/Yoti.Auth.Tests/TestData/ShareFailure.json
test/Yoti.Auth.Tests/TestData/ShareFailureMinimal.json
test/Yoti.Auth.Tests/TestData/ShareFailureMissingErrorCode.json
test/Yoti.Auth.Tests/TestData/ShareFailureMissingErrorDetails.json
test/Yoti.Auth.Tests/Yoti.Auth.Tests.csproj
test/Yoti.Auth.Tests/YotiClientEngineTests.cs

- Items to YotiProfileException:
- ErrorCode
- ResponseContent
Example:
```csharp
using Yoti.Auth.Exceptions;
try
{
ActivityDetails activityDetails = client.GetActivityDetails(encryptedToken);
}
catch (YotiProfileException profileEx)
{
string errorCode = profileEx.ErrorCode;
string responseContent= profileEx.ResponseContent;
}
```

Release 3.12.0
